### ISSUE TITLE
On the ShapeNet hdf5 dataset

### ISSUE THREAD

**Issue by NoahDDavis** [llien30/point_cloud_anomaly_detection#1]
Hi, congrats on the nice work! I am trying to run the code but am stuck by the data set loading. Could you please provide the link where I can download the ShapeNet hdf5 dataset that was used in your code?

**Comment by llien30** [comment]
Thank you for reading our work and reaching out!

You can download the original dataset from [here](https://shapenet.org/).
And they are providing the randomly sampled (2048 point) data: https://github.com/AnTao97/UnsupervisedPointCloudReconstruction

You can use whichever you like to run our code! (First one you need sampling)
Thanks!

**Comment by NoahDDavis** [comment]
Thanks very much for your reply!

I tried the second one,  it seems that I need to do some preprocessing on the downloaded h5 file from https://github.com/AnTao97/UnsupervisedPointCloudReconstruction ?
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/101535753/159043517-ad8232e3-9ef5-41aa-ac6a-5946c230613d.png">

**Comment by llien30** [comment]
I don't think so.
I think you had some errors during the downloading phase.

**Comment by NoahDDavis** [comment]
Thanks for your reply! 
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/101535753/159054596-219d47aa-c07a-4229-b3ce-ec7560366c6e.png">
I download the ShapeNet hdf5 file from the TsinghuaCloud Link of https://github.com/AnTao97/UnsupervisedPointCloudReconstruction and the above is the dataset overview. I think maybe I need to turn it into structure like shapenetcorev2_hdf5_2048/train/class_name.h5?

**Comment by llien30** [comment]
Sorry, maybe you are right.

**Comment by NoahDDavis** [comment]
Alright, thanks for your information!
