### ISSUE TITLE
Epoch for training?

### ISSUE THREAD

**Issue by NoahDDavis** [llien30/point_cloud_anomaly_detection#3]
Hi, congrats on the nice work and code. I have a question: do you train 300 epochs for all the leave-one-out experiments? Or you1 use different epochs for different experiments? Thanks.

**Comment by NoahDDavis** [comment]
It seems that you train for 300 epochs and then choose the model which has the best performance, right?

**Comment by llien30** [comment]
Thank you for reaching out!
I used 300 epochs for all the experiments. I didn't do the selection.
